name: Build PSP YouTube 0.2v

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pspdev/pspdev:latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update packages
        run: |
          psp-pacman -Syu --noconfirm || true

      - name: Install intraFont
        run: |
          psp-pacman -S --needed --noconfirm libintrafont

      - name: Build
        run: |
          make clean || true
          make

      - name: Prepare PSP folder
        run: |
          mkdir -p release/PSP/GAME/PSPYouTube
          cp EBOOT.PBP release/PSP/GAME/PSPYouTube/

      - name: Upload EBOOT
        uses: actions/upload-artifact@v4
        with:
          name: PSP-YouTube-0.2v
          path: release/